{
 "title": "TestFuzn – Load Test Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "test_run_id",
    "query": {
     "query": "    import \"influxdata/influxdb/schema\"\r\n    schema.tagValues(\r\n      bucket: \"TestFuzn\",\r\n      tag: \"test_run_id\",\r\n      start: -30d\r\n    )"
    }
   }
  ]
 },
 "panels": [
  { "title": "Request Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"TestFuzn\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"scenario_metrics\")\n  |> filter(fn: (r) => r._field == \"request_count\")\n  |> filter(fn: (r) => r.test_run_id == \"${test_run_id}\")\n  |> last()\n  |> keep(columns: [\"_value\"])\n  |> rename(columns: {_value: \"Request Count\"})"
    }
   ]
  },
  {
   "title": "Successful Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"TestFuzn\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"scenario_metrics\")\n  |> filter(fn: (r) => r._field == \"ok_request_count\")\n  |> filter(fn: (r) => r.test_run_id == \"${test_run_id}\")\n  |> last()\n  |> keep(columns: [\"_value\"])\n  |> rename(columns: {_value: \"OK Request Count\"})"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"TestFuzn\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"scenario_metrics\")\r\n  |> filter(fn: (r) => r._field == \"failed_request_count\")\r\n  |> filter(fn: (r) => r.test_run_id == \"${test_run_id}\")\r\n  |> last()\r\n    |> keep(columns: [\"_value\"])\r\n  |> rename(columns: {_value: \"Failed Request Count\"})"
    }
   ]
  },
  {
   "title": "Total RPS",
   "type": "stat",
   "description": "Total Requests per Second",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"TestFuzn\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"scenario_metrics\")\r\n  |> filter(fn: (r) => r._field == \"requests_per_second\")\r\n  |> filter(fn: (r) => r.test_run_id == \"${test_run_id}\")\r\n  |> last()\r\n    |> keep(columns: [\"_value\"])\r\n  |> rename(columns: {_value: \"Total Requests per Second\"})"
    }
   ]
  },
  {
   "title": "Successful RPS",
   "type": "stat",
   "description": "Successful Requests per Second",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"TestFuzn\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"scenario_metrics\")\r\n  |> filter(fn: (r) => r._field == \"ok_requests_per_second\")\r\n  |> filter(fn: (r) => r.test_run_id == \"${test_run_id}\")\r\n  |> last()\r\n    |> keep(columns: [\"_value\"])\r\n  |> rename(columns: {_value: \"Successful RPS\"})"
    }
   ]
  },
  {
   "title": "Failed RPS",
   "type": "stat",
   "description": "Failed Requests per Second",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"TestFuzn\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"scenario_metrics\")\r\n  |> filter(fn: (r) => r._field == \"failed_requests_per_second\")\r\n  |> filter(fn: (r) => r.test_run_id == \"${test_run_id}\")\r\n  |> last()\r\n    |> keep(columns: [\"_value\"])\r\n  |> rename(columns: {_value: \"Failed RPS\"})"
    }
   ]
  },
  {
   "title": "Throughput (Requests per Second)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Requests Per Second (OK)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 18, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "testStart = from(bucket: \"TestFuzn\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"scenario_metrics\")\r\n  |> filter(fn: (r) => r._field == \"requests_per_second\")\r\n  |> filter(fn: (r) => r.test_run_id == \"${test_run_id}\")\r\n  |> first()\r\n  |> findRecord(fn: (key) => true, idx: 0)\r\n\r\n  from(bucket: \"TestFuzn\")\r\n  |> range(start: testStart._time)\r\n  |> filter(fn: (r) => r._measurement == \"scenario_metrics\")\r\n  |> filter(fn: (r) => r._field == \"requests_per_second\")\r\n  |> filter(fn: (r) => r.test_run_id == \"${test_run_id}\")"
    },
    {
     "query": "testStart = from(bucket: \"TestFuzn\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"scenario_metrics\")\n  |> filter(fn: (r) => r._field == \"ok_requests_per_second\")\n  |> filter(fn: (r) => r.test_run_id == \"${test_run_id}\")\n  |> first()\n  |> findRecord(fn: (key) => true, idx: 0)\n\nfrom(bucket: \"TestFuzn\")\n  |> range(start: testStart._time)\n  |> filter(fn: (r) => r._measurement == \"scenario_metrics\")\n  |> filter(fn: (r) => r._field == \"ok_requests_per_second\")\n  |> filter(fn: (r) => r.test_run_id == \"${test_run_id}\")"
    },
    {
     "query": "testStart = from(bucket: \"TestFuzn\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"scenario_metrics\")\r\n  |> filter(fn: (r) => r._field == \"failed_requests_per_second\")\r\n  |> filter(fn: (r) => r.test_run_id == \"${test_run_id}\")\r\n  |> first()\r\n  |> findRecord(fn: (key) => true, idx: 0)\r\n\r\n  from(bucket: \"TestFuzn\")\r\n  |> range(start: testStart._time)\r\n  |> filter(fn: (r) => r._measurement == \"scenario_metrics\")\r\n  |> filter(fn: (r) => r._field == \"failed_requests_per_second\")\r\n  |> filter(fn: (r) => r.test_run_id == \"${test_run_id}\")"
    }
   ]
  },
  { "title": "Response Time Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Mean (ms)",
   "type": "stat",
   "description": "OK - Mean Response Time (ms)",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"TestFuzn\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"scenario_metrics\")\r\n  |> filter(fn: (r) => r._field == \"ok_response_time_mean_ms\")\r\n  |> filter(fn: (r) => r.test_run_id == \"${test_run_id}\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])\r\n  |> rename(columns: {_value: \"Mean\"})"
    }
   ]
  },
  {
   "title": "Median (ms)",
   "type": "stat",
   "description": "OK - Median Response Time (ms)",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"TestFuzn\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"scenario_metrics\")\r\n  |> filter(fn: (r) => r._field == \"ok_response_time_median_ms\")\r\n  |> filter(fn: (r) => r.test_run_id == \"${test_run_id}\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])\r\n  |> rename(columns: {_value: \"Median\"})"
    }
   ]
  },
  {
   "title": "P75 (ms)",
   "type": "stat",
   "description": "OK - 95 Percentile Response Time (ms)",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"TestFuzn\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"scenario_metrics\")\r\n  |> filter(fn: (r) => r._field == \"ok_response_time_percentile_75_ms\")\r\n  |> filter(fn: (r) => r.test_run_id == \"${test_run_id}\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])\r\n  |> rename(columns: {_value: \"P75\"})"
    }
   ]
  },
  {
   "title": "P95 (ms)",
   "type": "stat",
   "description": "OK - 95 Percentile Response Time (ms)",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"TestFuzn\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"scenario_metrics\")\r\n  |> filter(fn: (r) => r._field == \"ok_response_time_percentile_95_ms\")\r\n  |> filter(fn: (r) => r.test_run_id == \"${test_run_id}\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])\r\n  |> rename(columns: {_value: \"P95\"})"
    }
   ]
  },
  {
   "title": "P99 (ms)",
   "type": "stat",
   "description": "OK - 99 Percentile Response Time (ms)",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"TestFuzn\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"scenario_metrics\")\r\n  |> filter(fn: (r) => r._field == \"ok_response_time_percentile_99_ms\")\r\n  |> filter(fn: (r) => r.test_run_id == \"${test_run_id}\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])\r\n  |> rename(columns: {_value: \"P99\"})"
    }
   ]
  },
  {
   "title": "Min (ms)",
   "type": "stat",
   "description": "OK - Min Response Time (ms)",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"TestFuzn\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"scenario_metrics\")\r\n  |> filter(fn: (r) => r._field == \"ok_response_time_min_ms\")\r\n  |> filter(fn: (r) => r.test_run_id == \"${test_run_id}\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])\r\n  |> rename(columns: {_value: \"Min\"})"
    }
   ]
  },
  {
   "title": "Max (ms)",
   "type": "stat",
   "description": "OK - Max Response Time (ms)",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"TestFuzn\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"scenario_metrics\")\r\n  |> filter(fn: (r) => r._field == \"ok_response_time_max_ms\")\r\n  |> filter(fn: (r) => r.test_run_id == \"${test_run_id}\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])\r\n  |> rename(columns: {_value: \"Max\"})"
    }
   ]
  },
  {
   "title": "StdDev (ms)",
   "type": "stat",
   "description": "OK - Standard Devation (ms)",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"TestFuzn\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"scenario_metrics\")\r\n  |> filter(fn: (r) => r._field == \"ok_response_time_stddev_ms\")\r\n  |> filter(fn: (r) => r.test_run_id == \"${test_run_id}\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])\r\n  |> rename(columns: {_value: \"StdDev\"})"
    }
   ]
  }
 ]
}