using System.Text;
using TestFusion.Internals.ConsoleOutput;
using TestFusion.Contracts.Reports;
using TestFusion.Results.Feature;
using TestFusion.Internals.Reports.EmbeddedResources;

namespace TestFusion.Internals.Reports;

internal class FeatureHtmlReportWriter : IFeatureReport
{
    public async Task WriteReport(FeatureReportData featureReportData)
    {
        try
        {
            await IncludeEmbeddedResources(featureReportData);

            var filePath = Path.Combine(featureReportData.TestsOutputDirectory, "TestFusion_Report_Features.html");

            var htmlContent = GenerateHtmlReport(featureReportData);

            await File.WriteAllTextAsync(filePath, htmlContent);
        }
        catch (Exception ex)
        {
            // Log or handle the exception as needed
            throw new InvalidOperationException("Failed to write HTML report.", ex);
        }
    }

    private string GenerateHtmlReport(FeatureReportData featureReportData)
    {
        var builder = new StringBuilder();

        builder.AppendLine("<!DOCTYPE html>");
        builder.AppendLine("<html lang='en'>");
        builder.AppendLine("<head>");
        builder.AppendLine("<meta charset='UTF-8'>");
        builder.AppendLine("<meta name='viewport' content='width=device-width, initial-scale=1.0'>");
        builder.AppendLine("<title>Test Report</title>");
        builder.AppendLine("<style>");
        builder.AppendLine("body { font-family: Arial, sans-serif; margin: 20px; }");
        builder.AppendLine("h1, h2, h3 { color: #333; }");
        builder.AppendLine("li { list-style-type: none; }");
        builder.AppendLine(".summary { margin-bottom: 20px; }");
        builder.AppendLine(".collapsible { cursor: pointer; padding: 10px; border: none; text-align: left; outline: none; background-color: #f1f1f1; margin-bottom: 5px; display: flex; align-items: center; }");
        builder.AppendLine(".collapsible::before { content: '▼'; margin-right: 10px; transition: transform 0.2s; }");
        builder.AppendLine(".collapsible.collapsed::before { content: '▶'; transform: rotate(90deg); }");
        builder.AppendLine(".content { display: block; padding-left: 20px; }");
        builder.AppendLine(".collapsed + .content { display: none; }");
        builder.AppendLine(".passed { color: green; }");
        builder.AppendLine(".failed { color: red; }");
        builder.AppendLine(".skipped { color: orange; }");
        builder.AppendLine(".icon { margin-right: 5px; }");
        builder.AppendLine(".hierarchy { margin-left: 20px; }");
        builder.AppendLine("</style>");
        builder.AppendLine("<script>");
        builder.AppendLine("document.addEventListener('DOMContentLoaded', function() {");
        builder.AppendLine("  document.querySelectorAll('.collapsible').forEach(function(button) {");
        builder.AppendLine("    button.addEventListener('click', function() {");
        builder.AppendLine("      this.classList.toggle('collapsed');");
        builder.AppendLine("      var content = this.nextElementSibling;");
        builder.AppendLine("      content.style.display = content.style.display === 'block' ? 'none' : 'block';");
        builder.AppendLine("    });");
        builder.AppendLine("  });");
        builder.AppendLine("});");
        builder.AppendLine("</script>");
        builder.AppendLine("</head>");
        builder.AppendLine("<body>");

        // Header
        builder.AppendLine($"<h1>Feature Tests Report</h1>");
        builder.AppendLine($"<p>Generated by TestFusion on {DateTime.Now}</p>");
        builder.AppendLine($"<p>Test Suite: <strong>{featureReportData.TestSuiteName}</strong></p>");
        builder.AppendLine($"<p>Test Run ID: <strong>{featureReportData.TestRunId}</strong></p>");

        // Summary
        var totalFeatures = featureReportData.Results.FeatureResults.Count;
        var totalScenarios = featureReportData.Results.FeatureResults.Sum(f => f.Value.ScenarioResults.Count);
        var totalPassedScenarios = featureReportData.Results.FeatureResults.Sum(f => f.Value.ScenarioResults.Count(s => s.Status == ScenarioStatus.Passed));
        var totalFailedScenarios = totalScenarios - totalPassedScenarios;

        builder.AppendLine("<div class='summary'>");
        builder.AppendLine($"<p>Total Features: {totalFeatures}</p>");
        builder.AppendLine($"<p>Total Scenarios: {totalScenarios}</p>");
        builder.AppendLine($"<p>Passed Scenarios: <span class='passed'>{totalPassedScenarios}</span></p>");
        builder.AppendLine($"<p>Failed Scenarios: <span class='failed'>{totalFailedScenarios}</span></p>");
        builder.AppendLine("</div>");

        // Features
        foreach (var featureResult in featureReportData.Results.FeatureResults)
        {
            builder.AppendLine($"<button class='collapsible'>Feature: {featureResult.Key}</button>");
            builder.AppendLine("<div class='content'>");

            foreach (var scenarioResult in featureResult.Value.ScenarioResults)
            {
                builder.AppendLine($"<button class='collapsible'>Scenario: {scenarioResult.Name} - <span class='{(scenarioResult.Status == ScenarioStatus.Passed ? "passed" : "failed")}'>{(scenarioResult.Status == ScenarioStatus.Passed ? "Passed" : "Failed")}</span></button>");
                builder.AppendLine("<div class='content'>");

                if (scenarioResult.HasInputData)
                {
                    foreach (var iteration in scenarioResult.IterationResults)
                    {
                        builder.AppendLine($"<button class='collapsible'>Input Data: <span class='{(iteration.Passed ? "passed" : "failed")}'>{(iteration.Passed ? "Passed" : "Failed")}</span></button>");
                        builder.AppendLine("<div class='content'>");
                        builder.AppendLine("<ul>");
                        builder.AppendLine($"<li>{(string.IsNullOrEmpty(iteration.InputData) ? " " : iteration.InputData)}</li>");
                        foreach (var stepResult in iteration.StepResults)
                        {
                            WriteStepResult(builder, stepResult.Value);
                        }
                        builder.AppendLine("</ul>");
                        builder.AppendLine("</div>");
                    }
                }
                else
                {
                    var iteration = scenarioResult.IterationResults.FirstOrDefault();
                    if (iteration != null)
                    {
                        builder.AppendLine("<ul>");
                        foreach (var stepResult in iteration.StepResults)
                        {
                            WriteStepResult(builder, stepResult.Value);
                        }
                        builder.AppendLine("</ul>");
                    }
                }

                builder.AppendLine("</div>");
            }

            builder.AppendLine("</div>");
        }

        builder.AppendLine("</body>");
        builder.AppendLine("</html>");

        return builder.ToString();
    }

    private void WriteStepResult(StringBuilder builder, StepResult stepResult)
    {
        builder.AppendLine($"<li><span class='icon'>{SymbolSet.MapStepStatus(stepResult.Status)}</span>Step: {stepResult.Name} - <span class='{stepResult.Status.ToString().ToLower()}'>{stepResult.Status}</span> - Duration: {stepResult.Duration.ToTestFusionResponseTime()}</li>");

        if (stepResult.Attachments != null && stepResult.Attachments.Count > 0)
        {
            builder.AppendLine("<ul>");
            foreach (var attachment in stepResult.Attachments)
            {
                var fileName = Path.GetFileName(attachment.Path);
                builder.AppendLine($"<li>Attachment: <a href=\"Attachments/{fileName}\" target=\"_blank\">{attachment.Name}</a></li>");
            }
            builder.AppendLine("</ul>");
        }
    }

    private async Task IncludeEmbeddedResources(FeatureReportData featureReportData)
    {
        await EmbeddedResourceHelper.WriteEmbeddedResourceToFile(
            "TestFusion.Internals.Reports.EmbeddedResources.Scripts.chart.js",
            Path.Combine(featureReportData.TestsOutputDirectory, "assets/scripts/chart.js"));
    }
}
